apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluentd
  namespace: kube-system
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: fluentd
    spec:
      containers:
      - name: fluentd-elasticsearch
        image: gcr.io/google_containers/fluentd-elasticsearch:1.9
        resources:
          limits:
            cpu: 100m
        env:
        - name: "FLUENTD_ARGS"
          value: "-qq"
        volumeMounts:
        - name: varlog
          mountPath: /varlog
        - name: containers
          mountPath: /mnt/ephemeral/docker/containers
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: containers
        hostPath:
          path: /mnt/ephemeral/docker/containers
