apiVersion: v1
kind: Pod
metadata:
  name: my-web-app
spec:  # specification of the pod's contents
  restartPolicy: Never
  containers:
  - name: my-web-app
    image: tetranoodle/docker-web
    ports:
    - containerPort: 80
