apiVersion: v1
kind: Service
metadata:
  name: my-web-app
  labels:
    run: my-web-app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    run: my-web-app

